codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 3
  round: down
  range:
    - 70
    - 85

  status:
    project: no
    patch: no
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no
